#!/bin/bash
###########
opt=$1	
case "$opt" in
	-a)
		ls -a | sort
		;;
	-h)
		ls -ad .*
		;;
	-hs)
		ls -adS .*
		;;
	-o)
		ls -d */
		;;
	-os)
		du -m --max-depth 1 | sort -rn
		;;
	-f)
		getfacl $2
		;;
	-m)
		mv $2 $3
		;;
	-d)
		rm -r $2
		;;
	-xo)
		sed -n 'p;n' $2
		;;
	-xe)
		sed -n 'n;p' $2
		;;
	-x)
		opt=p
		sed -n "${2:0:2},${2:3}$opt" < $3
		;;
	-u)
		
		opt=d
		newFile="new$3"
		sed -e "${2:0:2},${2:3}$opt" $3 > $newFile
		;;
	-pn)
        cat -n $2
        ;;
	-r)
        orString=$2
        newString=$3
        opt1=s
        opt2=g
        sed -i "$opt1/$orString/$newString/$opt2" $4
        ;;
	-c)
        orChar=$2
        newChar=$3
        opt1=s
        opt2=g
        sed -i "$opt1/$orChar/$newChar/$opt2" $4
        ;;
	-v)
        ls -l $2
        ;;
	-l)
        newFile="numbered$2"
        cat -n $2 > $newFile
        ;;
	-z)
        tac $2
        ;;
	-b)
        ls -lS | head -n 2
        ;;
	-s)
        ls -ls | head -n 2
        ;;
	-fa)
        ls -lS
        ;;
	-fd)
        ls -ls
        ;;
	-q)
        line=$2
        content=$3
        orFile=$4        
        replaceFile="replace$4"
        opt=s
        sed "$line$opt/.*/$content/" $orFile > $replaceFile
        ;;
	-mi)
        rev $2
        ;;
	-jb)
        orFile=$2
        text="$3"
        row=$4
        newFile="before$orFile"
        sed "$row i $text" $orFile > $newFile
        ;;
	-ja)
        orFile=$2
        text="$3"
        row=$(( $4 + 1 ))
        newFile="after$orFile"
        sed "$row i $text" $orFile > $newFile
        ;;
	-rd)
        diff -qr $2 $3
        ;;
    -slod)
        lsof -u $2 | sort 
        ;;
    -rc)
        orFile=$2
        col1=$3
        col2=$4
        newFile="colchange$orFile"
        awk "{$col1 = $col2; print}" $orFile > $newFile 
        ;;
    *)
        echo "Error!! Please check input!"
        ;;
esac
exit 1
